require 'sinatra'
require 'slim'

#handler: http get, will return a view index, generated by slim
get '/' do
	slim :index
end

#inline templates go after __END__
__END__

#all inline templates begin with @@
#layout is basic HTML5 setup
#yield renders whatever was requested by the handler
@@layout
doctype html
html
	head
		meta charset="utf-8"
		title Hacker Summary
		link rel="stylesheet" media="screen, projection" href="/style.css"
		/[if lt IE 9]
			script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"
	body
		h1 Hacker Summary
		== yield

@@index
h2 Hackathons
ul.upcoming
	li Stupid Shit Nobody Needs Hackathon
